spring:
  
  application:
    name: hotel-classification

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/hotel_db}
    username: ${DB_USERNAME:hotel_user}
    password: ${DB_PASSWORD:hotel_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

server:
  port: 8080

logging:
  level:
    ru.etu.hotel: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
